### ISSUE TITLE
Plugin not appearing in Project's Plugins

### ISSUE THREAD

**Issue by simonv3** [vickylance/godot-formatter#1]
I added the plugin to the addons folder:

![image](https://user-images.githubusercontent.com/485583/90988561-7dd8fd00-e548-11ea-946b-02efae1ab7f9.png)

but it's not appearing in the project's plugin list:

![image](https://user-images.githubusercontent.com/485583/90988268-6e58b480-e546-11ea-9c50-47b75248a50c.png)

Since I'm fairly new to Godot, I may very well be doing something wrong. 

I've ended up manually installing GDToolkit, and it looks like it works when I run `gdformat <script/path>`. It'd be great if I could get this working automatically!

**Comment by vickylance** [comment]
@simonv3  It should showup in the plugins window. When you copy the folder make sure both the formatter.gd and plugin.cfg is copied as well. https://github.com/vickylance/godot-formatter/tree/master/addons/formatter

That should make it show up in the plugins window.

Regarding the manual installation of GDToolkit. Its currently tricky to get it installed via the formatter itself. But if it doesnt work then as you installed it manually you can just do 

`which gdformat` if on OSX or Linux machine and
`where gdformat` if on windows machine and then just copy paste the resulting path in the formatter.gd file
in line no.4  `var gdformatter_path = "<path>"`

**Comment by simonv3** [comment]
Ah cool! Thanks. I had left out the plugin.cfg :+1: 

Looks like it's working now, and I can format all my files when I toggle it through the menu. Thanks!
